name: Bump Version Code
on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  bump-version-code:
    name: Bump Version Code
    if: startsWith(github.head_ref, 'release-please--branches--')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Bump version code
        run: |
          perl -pi -e 's/(versionCode\s*=\s*)(\d+)/$1.($2+1)/e' app/build.gradle.kts

      - name: Commit version code
        env:
          GH_TOKEN: ${{ secrets.SOMLENG_PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "dwilkie"
          git config user.email "dwilkie@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add app/build.gradle.kts
          git commit -m "Bump version code"
          git push
