on:
  pull_request:
    types: [opened]
    branches:
      - release-please--branches--*

jobs:
  increment-version-code:
    name: Increment Version Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Increment version code
        run: |
          perl -pi -e 's/(versionCode\s*=\s*)(\d+)/$1.($2+1)/e' app/build.gradle.kts

      - name: Commit version code
        env:
          GH_TOKEN: ${{ secrets.SOMLENG_PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add app/build.gradle.kts
          git commit -m "Bump version code"
          git push
